### ISSUE TITLE
no matching versions for query "latest"

### ISSUE THREAD

**Issue by daudfauzy98** [FadhlanHawali/Digitalent-Kominfo_Pendalaman-Rest-API#1]
Permisi mas, ini saya dapat error seperti di gambar ketika menjalankan `go build` di project Pendalaman Microservice kemarin.

![Golang Error](https://user-images.githubusercontent.com/71966505/96429004-a1f44a00-122a-11eb-8a4e-1233191e2b63.jpg)

Padahal import-nya sudah sesuai lokasi package-nya

![Golang Error 2](https://user-images.githubusercontent.com/71966505/96429253-f0094d80-122a-11eb-9516-5efddb6ce9a6.jpg)

**Comment by daudfauzy98** [comment]
Maaf mas, udah berhasil ditangani error-nya.. Ternyata tinggal dihapus file go.mod sm go.sum-nya, lalu di-init ulang go mod-nya di folder root project.. Sebelumnya file go.mod dan go.sum ada di folder menu-service..

**Comment by FadhlanHawali** [comment]
Muantaappp siapp
